"""
Central location for all hard coded data needed for tests.
"""

DOWNLOAD_OPTIONS_FROM_ALL_SERVICES = {
    # 'svc://nasa:srtm-3-arc-second': {},
    # 'svc://nasa:srtm-30-arc-second': {},
    'svc://noaa-ncdc:ghcn-daily': {
        'properties': [{
            'default': None,
            'description': 'parameter',
            'name': 'parameter',
            'range': [
                ['air_temperature:daily:mean', 'air_temperature:daily:mean'],
                ['air_temperature:daily:minimum', 'air_temperature:daily:minimum'],
                ['air_temperature:daily:total', 'air_temperature:daily:total'],
                ['rainfall:daily:total', 'rainfall:daily:total'],
                ['snow_depth:daily:total', 'snow_depth:daily:total'],
                ['snowfall:daily:total', 'snowfall:daily:total']],
            'type': 'ObjectSelector'},
            {'bounds': None,
             'default': None,
             'description': 'start date',
             'name': 'start',
             'type': 'Date'},
            {'bounds': None,
             'default': None,
             'description': 'end date',
             'name': 'end',
             'type': 'Date'}],
        'title': 'NCDC GHCN Daily Download Options'},
    'svc://noaa-ncdc:gsod': {
        'properties': [
            {'default': None,
             'description': 'parameter',
             'name': 'parameter',
             'range': [
                 ['air_temperature:daily:max', 'air_temperature:daily:max'],
                 ['air_temperature:daily:min', 'air_temperature:daily:min'],
                 ['rainfall:daily:total', 'rainfall:daily:total'],
                 ['snow_depth:daily:total', 'snow_depth:daily:total']],
             'type': 'ObjectSelector'},
            {'bounds': None,
             'default': None,
             'description': 'start date',
             'name': 'start',
             'type': 'Date'},
            {'bounds': None,
             'default': None,
             'description': 'end date',
             'name': 'end',
             'type': 'Date'}],
        'title': 'NCDC GSOD Download Options'},
    'svc://noaa-coast:coops-meteorological':
        {'properties': [
            {'default': None,
             'description': 'parameter',
             'name': 'parameter',
             'range': [
                 ['air_temperature', 'air_temperature'],
                 ['barometric_pressure', 'barometric_pressure'],
                 ['collective_rainfall', 'collective_rainfall'],
                 ['direction_of_sea_water_velocity', 'direction_of_sea_water_velocity'],
                 ['relative_humidity', 'relative_humidity'],
                 ['sea_water_electric_conductivity', 'sea_water_electric_conductivity'],
                 ['sea_water_speed', 'sea_water_speed'],
                 ['sea_water_temperature', 'sea_water_temperature'],
                 ['visibility_in_air', 'visibility_in_air'],
                 ['wind_from_direction', 'wind_from_direction'],
                 ['wind_speed', 'wind_speed'],
                 ['wind_speed_from_gust', 'wind_speed_from_gust']],
             'type': 'ObjectSelector'},
            {'bounds': None,
             'default': None,
             'description': 'start date',
             'name': 'start',
             'type': 'Date'},
            {'bounds': None,
             'default': None,
             'description': 'end date',
             'name': 'end',
             'type': 'Date'}
        ],
            'title': 'NOAA COOPS Met Download Options'},
    'svc://noaa-coast:coops-water':
        {'properties': [
            {'default': None,
             'description': 'parameter',
             'name': 'parameter',
             'range': [
                 ['predicted_waterLevel', 'predicted_waterLevel'],
                 ['sea_surface_height_amplitude', 'sea_surface_height_amplitude']
             ],
             'type': 'ObjectSelector'},
            {'bounds': None,
             'default': None,
             'description': 'start date',
             'name': 'start',
             'type': 'Date'},
            {'bounds': None,
             'default': None,
             'description': 'end date',
             'name': 'end',
             'type': 'Date'},
            {'default': 'R',
             'description': 'quality',
             'name': 'quality',
             'range': [
                 ['Preliminary', 'Preliminary'],
                 ['R', 'R'],
                 ['Verified', 'Verified']],
             'type': 'ObjectSelector'},
            {'default': '6',
             'description': 'time interval',
             'name': 'interval',
             'range': [['6', '6'], ['60', '60']],
             'type': 'ObjectSelector'},
            {'default': 'Mean Lower_Low Water',
             'description': 'datum',
             'name': 'datum',
             'range': [
                 ['Great Diurnal Range', 'Great Diurnal Range'],
                 ['Greenwich High Water Interval( in Hours)', 'Greenwich High Water Interval( in Hours)'],
                 ['Greenwich Low Water Interval( in Hours)', 'Greenwich Low Water Interval( in Hours)'],
                 ['Mean Diurnal High Water Inequality', 'Mean Diurnal High Water Inequality'],
                 ['Mean Diurnal Low Water Inequality', 'Mean Diurnal Low Water Inequality'],
                 ['Mean Diurnal Tide L0evel', 'Mean Diurnal Tide L0evel'],
                 ['Mean High Water', 'Mean High Water'],
                 ['Mean Higher - High Water', 'Mean Higher - High Water'],
                 ['Mean Low Water', 'Mean Low Water'],
                 ['Mean Lower_Low Water', 'Mean Lower_Low Water'],
                 ['Mean Range of Tide', 'Mean Range of Tide'],
                 ['Mean Sea Level', 'Mean Sea Level'],
                 ['Mean Tide Level', 'Mean Tide Level'],
                 ['North American Vertical Datum', 'North American Vertical Datum'],
                 ['Station Datum', 'Station Datum']],
             'type': 'ObjectSelector'}],
            'title': 'NOAA COOPS Water Download Options'},
    'svc://noaa-coast:ndbc':
        {'properties': [
            {'default': None,
             'description': 'parameter',
             'name': 'parameter',
             'range': [
                 ['air_pressure', 'air_pressure'],
                 ['air_temperature', 'air_temperature'],
                 ['eastward_wind', 'eastward_wind'],
                 ['northward_wind', 'northward_wind'],
                 ['sea_surface_temperature', 'sea_surface_temperature'],
                 ['water_level', 'water_level'],
                 ['wave_height', 'wave_height'],
                 ['wind_direction', 'wind_direction'],
                 ['wind_from_direction', 'wind_from_direction'],
                 ['wind_speed_of_gust', 'wind_speed_of_gust']],
             'type': 'ObjectSelector'},
            {'bounds': None,
             'default': None,
             'description': 'start date',
             'name': 'start',
             'type': 'Date'},
            {'bounds': None,
             'default': None,
             'description': 'end date',
             'name': 'end',
             'type': 'Date'}
        ],
            'title': 'NOAA National Data Buoy Center Download Options'},
    'svc://usgs-ned:1-arc-second': {},
    'svc://usgs-ned:13-arc-second': {},
    'svc://usgs-ned:19-arc-second': {},
    'svc://usgs-ned:alaska-2-arc-second': {},
    'svc://usgs-nlcd:2001': {},
    'svc://usgs-nlcd:2006': {},
    'svc://usgs-nlcd:2011': {},
    'svc://usgs-nwis:dv':
        {'properties': [
            {'default': None,
             'description': 'parameter',
             'name': 'parameter',
             'range': [
                 ['streamflow:mean:daily', 'streamflow:mean:daily'],
                 ['water_temperature:daily:max', 'water_temperature:daily:max'],
                 ['water_temperature:daily:mean', 'water_temperature:daily:mean'],
                 ['water_temperature:daily:min', 'water_temperature:daily:min']],
             'type': 'ObjectSelector'},
            {'bounds': None,
             'default': None,
             'description': 'start date',
             'name': 'start',
             'type': 'Date'},
            {'bounds': None,
             'default': None,
             'description': 'end date',
             'name': 'end',
             'type': 'Date'},
            {'default': 'P365D',
             'description': 'time period (e.g. P365D = 365 days or P4W = 4 weeks)',
             'name': 'period',
             'type': 'String'}],
            'title': 'NWIS Daily Values Service Download Options'},
    'svc://usgs-nwis:iv':
        {'properties': [
            {'default': None,
             'description': 'parameter',
             'name': 'parameter',
             'range': [
                 ['gage_height', 'gage_height'],
                 ['streamflow', 'streamflow'],
                 ['water_temperature', 'water_temperature']
             ],
             'type': 'ObjectSelector'},
            {'bounds': None,
             'default': None,
             'description': 'start date',
             'name': 'start',
             'type': 'Date'},
            {'bounds': None,
             'default': None,
             'description': 'end date',
             'name': 'end',
             'type': 'Date'},
            {'default': 'P365D',
             'description': 'time period (e.g. P365D = 365 days or P4W = 4 weeks)',
             'name': 'period',
             'type': 'String'}
        ],
            'title': 'NWIS Instantaneous Values Service Download Options'},
    'svc://cuahsi-hydroshare:hs_geo': {},
    'svc://cuahsi-hydroshare:hs_norm': {},
    'svc://noaa-ncep:ncep_gfs':
        {'properties': [
            {'default': None,
             'description': 'YYYYMMDD',
             'name': 'date',
             'type': 'String'},
            {'default': None,
             'description': 'Froecast Resolution',
             'name': 'res',
             'type': 'String'},
            {'default': None,
             'description': 'Forecast Cycle Runtime',
             'name': 'cycle',
             'type': 'String'},
            {'default': None,
             'description': 'Forecast start time (f###)',
             'name': 'start',
             'type': 'String'},
            {'default': None,
             'description': 'Forecast end time (f###)',
             'name': 'end',
             'type': 'String'},
            {'default': None,
             'description': 'Paramerter',
             'name': 'format',
             'range': [],
             'type': 'ObjectSelector'},
            {'default': None,
             'description': 'Parameter2',
             'name': 'type',
             'range': [['GDAS', 'GDAS'], ['GFS', 'GFS']],
             'type': 'ObjectSelector'},
            {'default': None,
             'description': 'Parameter3',
             'name': 'product',
             'range': [
                 ["0.50 deg 'full' file description", "0.50 deg 'full' file description"],
                 ['32km Lambert Conformal grid', '32km Lambert Conformal grid'],
                 ['Atmospheric Analysis', 'Atmospheric Analysis'],
                 ['Atmospheric Model Data', 'Atmospheric Model Data'],
                 ['BUFR Sounding Files per Station', 'BUFR Sounding Files per Station'],
                 ['Binary Universal Form for the Representation of meteorological data (BUFR)',
                  'Binary Universal Form for the Representation of meteorological data (BUFR)'],
                 ['GDAS', 'GDAS'],
                 ['GFS', 'GFS'],
                 ['Global longitude-latitude grid', 'Global longitude-latitude grid'],
                 ['MDL Extratropical Storm Surge', 'MDL Extratropical Storm Surge'],
                 ['MOS Aviation Product', 'MOS Aviation Product'],
                 ['Prepared BUFR files', 'Prepared BUFR files'],
                 ['Pressure Level Data', 'Pressure Level Data'],
                 ['Sigma Atmospheric Model Data', 'Sigma Atmospheric Model Data'],
                 ['Smart Initialization Guam', 'Smart Initialization Guam'],
                 ['Surface Analysis', 'Surface Analysis'],
                 ['Surface Boundary Conditions', 'Surface Boundary Conditions'],
                 ['Surface Flux', 'Surface Flux'],
                 ['T1534 Semi-Lagrangian grid', 'T1534 Semi-Lagrangian grid'],
                 ['Time Dependent Satellite Bias Correction',
                  'Time Dependent Satellite Bias Correction'],
                 ['Tropical Cyclone Vital Statistics',
                  'Tropical Cyclone Vital Statistics'],
                 ['WAFS/ICAO/International Exchange/FOS Grids',
                  'WAFS/ICAO/International Exchange/FOS Grids'],
                 ['World Area Forecast System', 'World Area Forecast System'],
                 ['global longitude-latitude grid (1.0 deg)',
                  'global longitude-latitude grid (1.0 deg)']
             ],
             'type': 'ObjectSelector'}],
            'title': 'NCEP GFS Service Download Options'},
    'svc://noaa-ncep:ncep_nam':
        {'properties': [
            {'default': None, 'description': 'YYYYMMDD',
             'name': 'date',
             'type': 'String'},
            {'default': None,
             'description': 'Froecast Resolution',
             'name': 'res',
             'type': 'String'},
            {'default': None,
             'description': 'Forecast Cycle Runtime',
             'name': 'cycle',
             'type': 'String'},
            {'default': None,
             'description': 'Forecast start time (f###)',
             'name': 'start',
             'type': 'String'},
            {'default': None,
             'description': 'Forecast end time (f###)',
             'name': 'end',
             'type': 'String'},
            {'default': None,
             'description': 'Paramerter',
             'name': 'format',
             'range': [],
             'type': 'ObjectSelector'},
            {'default': None,
             'description': 'Parameter2',
             'name': 'type',
             'range': [['NAM', 'NAM']],
             'type': 'ObjectSelector'},
            {'default': None,
             'description': 'Parameter3',
             'name': 'product',
             'range': [
                 ['NAM', 'NAM'],
                 ['NAM - Binary Universal Form for the Representation of meteorological data (BUFR)',
                  'NAM - Binary Universal Form for the Representation of meteorological data (BUFR)'],
                 ['NAM 104 AWIPS Grid (N. Hemisphere polar stereographic grid (NGM Super C grid))',
                  'NAM 104 AWIPS Grid (N. Hemisphere polar stereographic grid (NGM Super C grid))'],
                 ['NAM 181 AFWA Grid - Central America/Caribbean (12-km Resolution)',
                  'NAM 181 AFWA Grid - Central America/Caribbean (12-km Resolution)'],
                 ['NAM 182 AFWA Grid - North Pacific  (12-km Resolution)',
                  'NAM 182 AFWA Grid - North Pacific  (12-km Resolution)'],
                 ['NAM 190 Grid - CONUS (Staggered B-grid on rotated lat/lon grid using the 60 NAM hybrid levels'
                  '(NAM 12km Domain))',
                  'NAM 190 Grid - CONUS (Staggered B-grid on rotated lat/lon grid using the 60 NAM hybrid levels'
                  '(NAM 12km Domain))'],
                 ['NAM 190 Grid - CONUS (Staggered B-grid on rotated latitude/longitude grid (NAM 12km Domain))',
                  'NAM 190 Grid - CONUS (Staggered B-grid on rotated latitude/longitude grid (NAM 12km Domain))'],
                 ['NAM 195 Grid over Puerto Rico (2.5-km Resolution) (NAM Smartinit for NDFD)',
                  'NAM 195 Grid over Puerto Rico (2.5-km Resolution) (NAM Smartinit for NDFD)'],
                 ['NAM 196 Grid over Hawaii (2.5-km Resolution) (NAM Smartinit for NDFD)',
                  'NAM 196 Grid over Hawaii (2.5-km Resolution) (NAM Smartinit for NDFD)'],
                 ['NAM 197 Grid - CONUS (5-km Resolution) (NAM Smartinit for NDFD)',
                  'NAM 197 Grid - CONUS (5-km Resolution) (NAM Smartinit for NDFD)'],
                 ['NAM 198 Grid over Alaska (6-km Resolution) (NAM Smartinit for NDFD)',
                  'NAM 198 Grid over Alaska (6-km Resolution) (NAM Smartinit for NDFD)'],
                 ['NAM 211 AWIPS Grid - Regional - CONUS (81-km Resolution)',
                  'NAM 211 AWIPS Grid - Regional - CONUS (81-km Resolution)'],
                 ['NAM 212 AWIPS Grid - Regional - CONUS (Double Resolution (40-km Resolution))',
                  'NAM 212 AWIPS Grid - Regional - CONUS (Double Resolution (40-km Resolution))'],
                 ['NAM 215 AWIPS Grid - CONUS (20-km Resolution)',
                  'NAM 215 AWIPS Grid - CONUS (20-km Resolution)'],
                 ['NAM 216 AWIPS Grid - Regional - Alaska (45-km Resolution)',
                  'NAM 216 AWIPS Grid - Regional - Alaska (45-km Resolution)'],
                 ['NAM 218 AWIPS Grid - CONUS (12-km Resolution; full complement of pressure level fields and some '
                  'surface-based fields)',
                  'NAM 218 AWIPS Grid - CONUS (12-km Resolution; full complement of pressure level fields and some '
                  'surface-based fields)'],
                 ['NAM 218 AWIPS Grid - CONUS (12-km Resolution; full complement of surface-based fields)',
                  'NAM 218 AWIPS Grid - CONUS (12-km Resolution; full complement of surface-based fields)'],
                 ['NAM 218 AWIPS Grid - CONUS - (12-km Resolution) (GOES Simulated Brightness Temp.)',
                  'NAM 218 AWIPS Grid - CONUS - (12-km Resolution) (GOES Simulated Brightness Temp.)'],
                 ['NAM 221 AWIPS Grid - High Resolution North American Master Grid (32-km Resolution)',
                  'NAM 221 AWIPS Grid - High Resolution North American Master Grid (32-km Resolution)'],
                 ['NAM 221 AWIPS Grid - N. American Master (32-km Resolution) (GOES Simulated Brightness Temp.)',
                  'NAM 221 AWIPS Grid - N. American Master (32-km Resolution) (GOES Simulated Brightness Temp.)'],
                 ['NAM 242 AWIPS Grid - Over Alaska (11.25 KM Resolution; full complement of pressure level fields and '
                  'some surface-based fields)',
                  'NAM 242 AWIPS Grid - Over Alaska (11.25 KM Resolution; full complement of pressure level fields and '
                  'some surface-based fields)'],
                 ['NAM 242 AWIPS Grid - Over Alaska (11.25 KM Resolution; full complement of surface-based fields)',
                  'NAM 242 AWIPS Grid - Over Alaska (11.25 KM Resolution; full complement of surface-based fields)'],
                 ['NAM 243 AWIPS Grid - Eastern North Pacific (40-km Resolution) (GOES Simulated Brightness Temp.)',
                  'NAM 243 AWIPS Grid - Eastern North Pacific (40-km Resolution) (GOES Simulated Brightness Temp.)'],
                 ['NAM 243 AWIPS Grid - Eastern North Pacific (Double Resolution (40-km Resolution))',
                  'NAM 243 AWIPS Grid - Eastern North Pacific (Double Resolution (40-km Resolution))'],
                 ['NAM IMS Snow Grid (24-km Resolution)',
                  'NAM IMS Snow Grid (24-km Resolution)'],
                 ['NAM MOS', 'NAM MOS'],
                 ['NAM NEST - FIRE WEATHER (1.33 km CONUS / 1.5 km Alaska Resolution)',
                  'NAM NEST - FIRE WEATHER (1.33 km CONUS / 1.5 km Alaska Resolution)'],
                 ['NAM NEST over ALASKA (6 km Resolution - Grid 198)',
                  'NAM NEST over ALASKA (6 km Resolution - Grid 198)'],
                 ['NAM NEST over CONUS (5 km Resolution - Grid 227)',
                  'NAM NEST over CONUS (5 km Resolution - Grid 227)'],
                 ['NAM NEST over HAWAII (3 km Resolution - Grid 196)',
                  'NAM NEST over HAWAII (3 km Resolution - Grid 196)'],
                 ['NAM NEST over PUERTO RICO (3 km Resolution - Grid 194)',
                  'NAM NEST over PUERTO RICO (3 km Resolution - Grid 194)']
             ],
             'type': 'ObjectSelector'}
        ],
            'title': 'NCEP NAM Service Download Options'},
    'svc://wmts:seamless_imagery':
        {'title': 'Web Mercator Tile Service Download Options',
         'properties': [
             {'name': 'url',
              'type': 'ObjectSelector',
              'description': '',
              'default': 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/'
                         '{Z}/{Y}/{X}',
              'range': [
                  ['http://c.tile.openstreetmap.org/{Z}/{X}/{Y}.png',
                   'http://c.tile.openstreetmap.org/{Z}/{X}/{Y}.png'],
                  ['http://tile.stamen.com/terrain/{Z}/{X}/{Y}.png',
                   'http://tile.stamen.com/terrain/{Z}/{X}/{Y}.png'],
                  ['https://s.basemaps.cartocdn.com/light_all/{Z}/{X}/{Y}.png',
                   'https://s.basemaps.cartocdn.com/light_all/{Z}/{X}/{Y}.png'],
                  ['https://server.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer/tile/{Z}/{Y}/{X}',
                   'https://server.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer/tile/{Z}/{Y}/{X}'],
                  ['https://server.arcgisonline.com/ArcGIS/rest/services/Ocean_Basemap/MapServer/tile/{Z}/{Y}/{X}',
                   'https://server.arcgisonline.com/ArcGIS/rest/services/Ocean_Basemap/MapServer/tile/{Z}/{Y}/{X}'],
                  ['https://server.arcgisonline.com/ArcGIS/rest/services/USA_Topo_Maps/MapServer/tile/{Z}/{Y}/{X}',
                   'https://server.arcgisonline.com/ArcGIS/rest/services/USA_Topo_Maps/MapServer/tile/{Z}/{Y}/{X}'],
                  ['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{Z}/{Y}/{X}',
                   'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{Z}/{Y}/{X}'],
                  ['https://server.arcgisonline.com/ArcGIS/rest/services/World_Physical_Map/MapServer/tile/'
                   '{Z}/{Y}/{X}',
                   'https://server.arcgisonline.com/ArcGIS/rest/services/World_Physical_Map/MapServer/tile/'
                   '{Z}/{Y}/{X}'],
                  ['https://server.arcgisonline.com/ArcGIS/rest/services/World_Shaded_Relief/MapServer/tile/'
                   '{Z}/{Y}/{X}',
                   'https://server.arcgisonline.com/ArcGIS/rest/services/World_Shaded_Relief/MapServer/tile/'
                   '{Z}/{Y}/{X}'],
                  ['https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{Z}/{Y}/{X}',
                   'https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{Z}/{Y}/{X}'],
                  ['https://server.arcgisonline.com/ArcGIS/rest/services/World_Terrain_Base/MapServer/tile/'
                   '{Z}/{Y}/{X}',
                   'https://server.arcgisonline.com/ArcGIS/rest/services/World_Terrain_Base/MapServer/tile/{'
                   'Z}/{Y}/{X}'],
                  ['https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{Z}/{Y}/{X}',
                   'https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{Z}/{Y}/{X}']
              ]},
             {'name': 'zoom_level',
              'type': 'Integer',
              'description': '',
              'default': 8,
              'bounds': None},
             {'name': 'bbox',
              'type': 'List',
              'description': '[x-min, y-max, x-max, y-min]',
              'default': [-180, 90, 180, -90]},
             {'name': 'crop_to_bbox',
              'type': 'Boolean',
              'description': None,
              'default': True},
             {'name': 'max_tiles',
              'type': 'Number',
              'description': 'Maximum number of tiles to allow (a number between 1 and `zoom_level`^4)',
              'default': 1000,
              'bounds': None}]}
}


SERVICES_FEATURE_COUNT = [
    # ('svc://nasa:srtm-3-arc-second', 14297, 1000),
    # ('svc://nasa:srtm-30-arc-second', 27, 10),
    ('svc://noaa-ncdc:ghcn-daily', 104126, 5000),
    ('svc://noaa-ncdc:gsod', 28754, 1500),
    ('svc://noaa-coast:coops-meteorological', 375, 50),
    ('svc://noaa-coast:coops-water', 234, 50),
    ('svc://noaa-coast:ndbc', 1136, 100),
    ('svc://usgs-ned:1-arc-second', 3644, 100),
    ('svc://usgs-ned:13-arc-second', 1245, 100),
    ('svc://usgs-ned:19-arc-second', 8358, 100),
    ('svc://usgs-ned:alaska-2-arc-second', 503, 50),
    ('svc://usgs-nlcd:2001', 147, 100),
    ('svc://usgs-nlcd:2006', 131, 100),
    ('svc://usgs-nlcd:2011', 203, 100),
    ('svc://usgs-nwis:dv', 36368, 1000),
    ('svc://usgs-nwis:iv', 19615, 1000),

]


CACHED_SERVICES = [s[0] for s in SERVICES_FEATURE_COUNT]

ALL_SERVICES = sorted(DOWNLOAD_OPTIONS_FROM_ALL_SERVICES.keys())

SERVICE = 'svc://usgs-nwis:iv'
FEATURE = 'f92ad0e35d04402ab1b1d4621b48a636'
DATASET = 'df5c3df3229441fa9c779443f03635e7'

DATASET_METADATA = {
    'download_status': 'downloaded',
    'download_message': 'success',
    'name': 'df5c3df3229441fa9c779443f03635e7',
    'file_format': 'timeseries-hdf5',
    'datatype': 'timeseries',
    'feature': 'f92ad0e35d04402ab1b1d4621b48a636',
    'collection': 'test_data',
    'download_options': '{"parameter": "streamflow"}',
    'dataset_type': 'download',
    'timezone': 'utc',
    'unit': 'ft3/s',
    'display_name': 'df5c3df3229441fa9c779443f03635e7',
    'parameter': 'streamflow',
    'metadata': {}
}

SERVICE_FEATURE_DOWNLOAD_OPTIONS = [
    # ('svc://nasa:srtm-3-arc-second/G1034711987-LPDAAC_ECS' , None),
    # ('svc://nasa:srtm-30-arc-second/G1005651728-LPDAAC_ECS', None),
    ('svc://noaa-ncdc:ghcn-daily/ACW00011604', {'parameter': 'air_temperature:daily:total', 'start': '1949-01-01', 'end': '1949-01-02'}),
    ('svc://noaa-ncdc:gsod/717580-99999', {'parameter': 'air_temperature:daily:max', 'start': '2016-01-01', 'end': '2016-01-02'}),
    ('svc://noaa-coast:coops-meteorological/1611400', {'parameter': 'air_temperature', 'start': '2015-05-23', 'end': '2015-05-24'}),
    ('svc://noaa-coast:coops-water/1611400', {'parameter': 'predicted_waterLevel', 'start': '2015-05-23', 'end': '2015-05-24'}),
    ('svc://noaa-coast:ndbc/0Y2W3', {'parameter': 'air_pressure', 'start': '2015-05-23', 'end': '2015-05-24'}),
    ('svc://usgs-ned:1-arc-second/581d2134e4b08da350d52cb0', None),
    ('svc://usgs-ned:13-arc-second/581d2134e4b08da350d52caf', None),
    ('svc://usgs-ned:19-arc-second/581d2561e4b08da350d5a3b2', None),
    ('svc://usgs-ned:alaska-2-arc-second/581d276ee4b08da350d5decb', None),
    ('svc://usgs-nlcd:2001/5a1c65a5e4b09fc93dd648f1', None),
    ('svc://usgs-nlcd:2006/5a1c35b6e4b09fc93dd64011', None),
    ('svc://usgs-nlcd:2011/5a1c31abe4b09fc93dd6381c', None),
    ('svc://usgs-nwis:dv/01010000', {'parameter': 'streamflow:mean:daily', 'start': '2016-01-01', 'end': '2016-01-02'}),
    ('svc://usgs-nwis:iv/01010000', {'parameter': 'gage_height', 'start': '2016-01-01', 'end': '2016-01-02'}),
]
