"""API functions related to Providers

Providers are inferred by aggregating information from service plugins.
"""
from .. import util
from jsonrpc import dispatcher

@dispatcher.add_method
def get_providers(name=None, **kwargs):
    """Return list of Providers. 

    This list is generated by inspecting each available Service plugin and aggregating.

    Parameters
    ----------
    name : ``None`` or str,
        The name of the provider. If ``None`` then return all.

    Returns
    -------
    providers : list,
        A python list representation of the providers
    """
    services = util.load_drivers('services')
    providers = {service.metadata['provider']['name']:service.metadata['provider'] for service in services.itervalues()}

    if name is not None:
        providers = [provider for provider in providers if provider['name']==name]

    return providers