"""API functions related to Providers

Providers are inferred from 
"""
from .. import util

@util.jsonify
def get_providers(id=None, **kwargs):
    """Return list of Providers. 

    This list is generated by inspecting each available Service plugin and aggregating.
    """
    services = util.load_drivers('services')
    providers = {service.metadata['provider']['id']:service.metadata['provider'] for service in services.itervalues()}

    if id:
        providers = [provider for provider in providers if provider['id']==name]

    return providers